/** \file
 *  This C source file was generated by $ANTLR version 3.1.1
 *
 *     -  From the grammar source file : NMakeExpression.g3pl
 *     -                            On : 2009-01-28 18:57:13
 *     -                 for the lexer : NMakeExpressionLexerLexer *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "NMakeExpressionLexer.h"
/* ----------------------------------------- */


/** String literals used by NMakeExpressionLexer that we must do things like MATCHS() with.
 *  C will normally just lay down 8 bit characters, and you can use L"xxx" to
 *  get wchar_t, but wchar_t is 16 bits on Windows, which is not UTF32 and so
 *  we perform this little trick of defining the literals as arrays of UINT32
 *  and passing in the address of these.
 */
static ANTLR3_UCHAR	lit_1[]  = { 0x26, 0x26,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_2[]  = { 0x7C, 0x7C,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_3[]  = { 0x3D, 0x3D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_4[]  = { 0x21, 0x3D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_5[]  = { 0x3C, 0x3D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_6[]  = { 0x3E, 0x3D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_7[]  = { 0x3C, 0x3C,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_8[]  = { 0x3E, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_9[]  = { 0x45, 0x58, 0x49, 0x53, 0x54,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_10[]  = { 0x44, 0x45, 0x46, 0x49, 0x4E, 0x45, 0x44,  ANTLR3_STRING_TERMINATOR};




/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */
 
#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pNMakeExpressionLexer_##scope##_SCOPE
#define SCOPE_STACK(scope)  pNMakeExpressionLexer_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pNMakeExpressionLexer_##scope##Top
#define	SCOPE_SIZE(scope)			(ctx->SCOPE_STACK(scope)->size(ctx->SCOPE_STACK(scope)))
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

 
/* Macros for accessing things in a lexer
 */
#undef	    LEXER
#undef	    RECOGNIZER		    
#undef	    RULEMEMO		    
#undef	    GETCHARINDEX
#undef	    GETLINE
#undef	    GETCHARPOSITIONINLINE
#undef	    EMIT
#undef	    EMITNEW
#undef	    MATCHC
#undef	    MATCHS
#undef	    MATCHRANGE
#undef	    LTOKEN
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    INPUT
#undef	    STRSTREAM
#undef	    LA
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    LRECOVER
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    BACKTRACKING
#undef		MATCHANY
#undef		MEMOIZE
#undef		HAVEPARSEDRULE
#undef		GETTEXT
#undef		INDEX
#undef		SEEK
#undef		PUSHSTREAM
#undef		POPSTREAM
#undef		SETTEXT
#undef		SETTEXT8

#define	    LEXER					ctx->pLexer
#define	    RECOGNIZER			    LEXER->rec
#define		LEXSTATE				RECOGNIZER->state
#define		TOKSOURCE				LEXSTATE->tokSource
#define	    GETCHARINDEX()			LEXER->getCharIndex(LEXER)
#define	    GETLINE()				LEXER->getLine(LEXER)
#define	    GETTEXT()				LEXER->getText(LEXER)
#define	    GETCHARPOSITIONINLINE() LEXER->getCharPositionInLine(LEXER)
#define	    EMIT()					LEXSTATE->type = _type; LEXER->emit(LEXER)
#define	    EMITNEW(t)				LEXER->emitNew(LEXER, t)
#define	    MATCHC(c)				LEXER->matchc(LEXER, c)
#define	    MATCHS(s)				LEXER->matchs(LEXER, s)
#define	    MATCHRANGE(c1,c2)	    LEXER->matchRange(LEXER, c1, c2)
#define	    MATCHANY()				LEXER->matchAny(LEXER)
#define	    LTOKEN  				LEXSTATE->token
#define	    HASFAILED()				(LEXSTATE->failed == ANTLR3_TRUE)
#define	    BACKTRACKING			LEXSTATE->backtracking
#define	    FAILEDFLAG				LEXSTATE->failed
#define	    INPUT					LEXER->input
#define	    STRSTREAM				INPUT
#define		ISTREAM					INPUT->istream
#define		INDEX()					ISTREAM->index(ISTREAM)
#define		SEEK(n)					ISTREAM->seek(ISTREAM, n)
#define	    EOF_TOKEN				&(LEXSTATE->tokSource->eofToken)
#define	    HASEXCEPTION()			(LEXSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				LEXSTATE->exception
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    LRECOVER()				LEXER->recover(LEXER)
#define	    MARK()					ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define		MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define		HAVEPARSEDRULE(r)		RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		PUSHSTREAM(str)			LEXER->pushCharStream(LEXER, str)
#define		POPSTREAM()				LEXER->popCharStream(LEXER)
#define		SETTEXT(str)			LEXSTATE->text = str
#define		SKIP()					LEXSTATE->token = &(TOKSOURCE->skipToken)
#define		USER1					LEXSTATE->user1
#define		USER2					LEXSTATE->user2
#define		USER3					LEXSTATE->user3
#define		CUSTOM					LEXSTATE->custom
#define		RULEMEMO				LEXSTATE->ruleMemo
#define		DBG						RECOGNIZER->debugger

/* If we have been told we can rely on the standard 8 bit or 16 bit input
 * stream, then we can define our macros to use the direct pointers
 * in the input object, which is much faster than indirect calls. This
 * is really only significant to lexers with a lot of fragment rules (which
 * do not place LA(1) in a temporary at the moment) and even then
 * only if there is a lot of input (order of say 1M or so).
 */
#if	defined(ANTLR3_INLINE_INPUT_ASCII) || defined(ANTLR3_INLINE_INPUT_UTF16)

# ifdef	ANTLR3_INLINE_INPUT_ASCII

/* 8 bit "ASCII" (actually any 8 bit character set) */

#  define	    NEXTCHAR			((pANTLR3_UINT8)(INPUT->nextChar))
#  define	    DATAP				((pANTLR3_UINT8)(INPUT->data))

# else

#  define	    NEXTCHAR			((pANTLR3_UINT16)(INPUT->nextChar)) 
#  define	    DATAP				((pANTLR3_UINT16)(INPUT->data))

# endif

# define	    LA(n) ((NEXTCHAR + n) > (DATAP + INPUT->sizeBuf) ? ANTLR3_CHARSTREAM_EOF : (ANTLR3_UCHAR)(*(NEXTCHAR + n - 1)))
# define	    CONSUME()											\
{																	\
    if	(NEXTCHAR < (DATAP + INPUT->sizeBuf))						\
    {																\
		INPUT->charPositionInLine++;								\
		if  ((ANTLR3_UCHAR)(*NEXTCHAR) == INPUT->newlineChar)		\
		{															\
			INPUT->line++;											\
			INPUT->charPositionInLine	= 0;						\
			INPUT->currentLine		= (void *)(NEXTCHAR + 1);		\
		}															\
		INPUT->nextChar = (void *)(NEXTCHAR + 1);					\
    }																\
}

#else

// Pick up the input character by calling the input stream implementation.
//
#define	    CONSUME()				INPUT->istream->consume(INPUT->istream)
#define	    LA(n)					INPUT->istream->_LA(INPUT->istream, n)

#endif
#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/* Forward declare the locally static matching functions we have generated and any predicate functions.
 */
static ANTLR3_INLINE  void	mBOOL_AND    (pNMakeExpressionLexer ctx);
static ANTLR3_INLINE  void	mBOOL_OR    (pNMakeExpressionLexer ctx);
static ANTLR3_INLINE  void	mBIT_AND    (pNMakeExpressionLexer ctx);
static ANTLR3_INLINE  void	mBIT_OR    (pNMakeExpressionLexer ctx);
static ANTLR3_INLINE  void	mEQUAL    (pNMakeExpressionLexer ctx);
static ANTLR3_INLINE  void	mNOT_EQUAL    (pNMakeExpressionLexer ctx);
static ANTLR3_INLINE  void	mLESS_THAN    (pNMakeExpressionLexer ctx);
static ANTLR3_INLINE  void	mGREATER_THAN    (pNMakeExpressionLexer ctx);
static ANTLR3_INLINE  void	mEQUAL_OR_LESS_THAN    (pNMakeExpressionLexer ctx);
static ANTLR3_INLINE  void	mEQUAL_OR_GREATER_THAN    (pNMakeExpressionLexer ctx);
static ANTLR3_INLINE  void	mSHIFT_LEFT    (pNMakeExpressionLexer ctx);
static ANTLR3_INLINE  void	mSHIFT_RIGHT    (pNMakeExpressionLexer ctx);
static ANTLR3_INLINE  void	mPLUS    (pNMakeExpressionLexer ctx);
static ANTLR3_INLINE  void	mMINUS    (pNMakeExpressionLexer ctx);
static ANTLR3_INLINE  void	mMULT    (pNMakeExpressionLexer ctx);
static ANTLR3_INLINE  void	mDIV    (pNMakeExpressionLexer ctx);
static ANTLR3_INLINE  void	mMOD    (pNMakeExpressionLexer ctx);
static ANTLR3_INLINE  void	mBIT_NOT    (pNMakeExpressionLexer ctx);
static ANTLR3_INLINE  void	mBOOL_NOT    (pNMakeExpressionLexer ctx);
static ANTLR3_INLINE  void	mT__32    (pNMakeExpressionLexer ctx);
static ANTLR3_INLINE  void	mT__33    (pNMakeExpressionLexer ctx);
static ANTLR3_INLINE  void	mNUMBER    (pNMakeExpressionLexer ctx);
static ANTLR3_INLINE  void	mWHITESPACE    (pNMakeExpressionLexer ctx);
static ANTLR3_INLINE  void	mLETTER    (pNMakeExpressionLexer ctx);
static ANTLR3_INLINE  void	mDIGIT    (pNMakeExpressionLexer ctx);
static ANTLR3_INLINE  void	mSPACE    (pNMakeExpressionLexer ctx);
static ANTLR3_INLINE  void	mEXIST    (pNMakeExpressionLexer ctx);
static ANTLR3_INLINE  void	mDEFINED    (pNMakeExpressionLexer ctx);
static ANTLR3_INLINE  void	mIDENTIFIER    (pNMakeExpressionLexer ctx);
static ANTLR3_INLINE  void	mSTRING    (pNMakeExpressionLexer ctx);
static ANTLR3_INLINE  void	mTokens    (pNMakeExpressionLexer ctx);
static void	NMakeExpressionLexerFree(pNMakeExpressionLexer ctx);

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */



static void
NMakeExpressionLexerFree  (pNMakeExpressionLexer ctx)
{
    LEXER->free(LEXER);
    
    ANTLR3_FREE(ctx);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "NMakeExpression.g3pl";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}

/** \brief Create a new lexer called NMakeExpressionLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \return 
 *     - Success pNMakeExpressionLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pNMakeExpressionLexer NMakeExpressionLexerNew         
(pANTLR3_INPUT_STREAM instream)
{
	// See if we can create a new lexer with the standard constructor
	//
	return NMakeExpressionLexerNewSSD(instream, NULL);
}

/** \brief Create a new lexer called NMakeExpressionLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \param[state] state Previously created shared recognizer stat
 * \return 
 *     - Success pNMakeExpressionLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pNMakeExpressionLexer NMakeExpressionLexerNewSSD         
(pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pNMakeExpressionLexer ctx; // Context structure we will build and return

    ctx = (pNMakeExpressionLexer) ANTLR3_CALLOC(1, sizeof(NMakeExpressionLexer));

    if  (ctx == NULL)
    {
        // Failed to allocate memory for lexer context
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * in base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 lexer function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function. 
     *
     * We don't use the macros defined in NMakeExpressionLexer.h here so you can get a sense
     * of what goes where.
     */
    
    /* Create a base lexer, using the supplied input stream
     */
    ctx->pLexer	= antlr3LexerNewStream(ANTLR3_SIZE_HINT, instream, state);
    
    /* Check that we allocated the memory correctly
     */
    if	(ctx->pLexer == NULL)
    {
		ANTLR3_FREE(ctx);
		return  NULL;
    }
    /* Install the implementation of our NMakeExpressionLexer interface
     */
    ctx->mBOOL_AND	= mBOOL_AND;
    ctx->mBOOL_OR	= mBOOL_OR;
    ctx->mBIT_AND	= mBIT_AND;
    ctx->mBIT_OR	= mBIT_OR;
    ctx->mEQUAL	= mEQUAL;
    ctx->mNOT_EQUAL	= mNOT_EQUAL;
    ctx->mLESS_THAN	= mLESS_THAN;
    ctx->mGREATER_THAN	= mGREATER_THAN;
    ctx->mEQUAL_OR_LESS_THAN	= mEQUAL_OR_LESS_THAN;
    ctx->mEQUAL_OR_GREATER_THAN	= mEQUAL_OR_GREATER_THAN;
    ctx->mSHIFT_LEFT	= mSHIFT_LEFT;
    ctx->mSHIFT_RIGHT	= mSHIFT_RIGHT;
    ctx->mPLUS	= mPLUS;
    ctx->mMINUS	= mMINUS;
    ctx->mMULT	= mMULT;
    ctx->mDIV	= mDIV;
    ctx->mMOD	= mMOD;
    ctx->mBIT_NOT	= mBIT_NOT;
    ctx->mBOOL_NOT	= mBOOL_NOT;
    ctx->mT__32	= mT__32;
    ctx->mT__33	= mT__33;
    ctx->mNUMBER	= mNUMBER;
    ctx->mWHITESPACE	= mWHITESPACE;
    ctx->mLETTER	= mLETTER;
    ctx->mDIGIT	= mDIGIT;
    ctx->mSPACE	= mSPACE;
    ctx->mEXIST	= mEXIST;
    ctx->mDEFINED	= mDEFINED;
    ctx->mIDENTIFIER	= mIDENTIFIER;
    ctx->mSTRING	= mSTRING;
    ctx->mTokens	= mTokens;
    
    /** When the nextToken() call is made to this lexer's pANTLR3_TOKEN_SOURCE
     *  it will call mTokens() in this generated code, and will pass it the ctx
     * pointer of this lexer, not the context of the base lexer, so store that now.
     */
    ctx->pLexer->ctx	    = ctx;
    
    /**Install the token matching function
     */
    ctx->pLexer->mTokens = (void (*) (void *))(mTokens);
    
    ctx->getGrammarFileName	= getGrammarFileName;
    ctx->free		= NMakeExpressionLexerFree;

    
    


    /* Return the newly built lexer to the caller
     */
    return  ctx;
}

/* =========================================================================
 * DFA tables for the lexer
 */
/** Static dfa state tables for Cyclic dfa:
 *    1:1: Tokens : ( BOOL_AND | BOOL_OR | BIT_AND | BIT_OR | EQUAL | NOT_EQUAL | LESS_THAN | GREATER_THAN | EQUAL_OR_LESS_THAN | EQUAL_OR_GREATER_THAN | SHIFT_LEFT | SHIFT_RIGHT | PLUS | MINUS | MULT | DIV | MOD | BIT_NOT | BOOL_NOT | T__32 | T__33 | NUMBER | WHITESPACE | EXIST | DEFINED | IDENTIFIER | STRING );
 */
static const ANTLR3_INT32 dfa8_eot[45] =
    {
	-1, 22, 24, -1, 26, 29, 32, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 19, 
	19, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 19, 19, 19, 
	19, 19, 19, 19, 19, -1, 19, 44, -1
    };
static const ANTLR3_INT32 dfa8_eof[45] =
    {
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa8_min[45] =
    {
	9, 38, 124, -1, 61, 60, 61, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 88, 
	69, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 73, 70, 83, 
	73, 84, 78, 9, 69, -1, 68, 48, -1
    };
static const ANTLR3_INT32 dfa8_max[45] =
    {
	126, 38, 124, -1, 61, 61, 62, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	88, 69, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 73, 70, 
	83, 73, 84, 78, 40, 69, -1, 68, 122, -1
    };
static const ANTLR3_INT32 dfa8_accept[45] =
    {
	-1, -1, -1, 5, -1, -1, -1, 13, 14, 15, 16, 17, 18, 20, 21, 22, 23, -1, 
	-1, 26, 27, 1, 3, 2, 4, 6, 19, 9, 11, 7, 10, 12, 8, -1, -1, -1, -1, -1, 
	-1, -1, -1, 24, -1, -1, 25
    };
static const ANTLR3_INT32 dfa8_special[45] =
    {	
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1
    };

/** Used when there is no transition table entry for a particular state */
#define dfa8_T_empty	    NULL

static const ANTLR3_INT32 dfa8_T0[] =
    {
	28, 27
    };static const ANTLR3_INT32 dfa8_T1[] =
    {
	34
    };static const ANTLR3_INT32 dfa8_T2[] =
    {
	16, 16, -1, 16, 16, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, 16, 4, 20, -1, -1, 11, 1, -1, 13, 14, 9, 7, -1, 8, 
	-1, 10, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, -1, -1, 5, 3, 6, -1, -1, 
	19, 19, 19, 18, 17, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 
	19, 19, 19, 19, 19, 19, 19, 19, -1, -1, -1, -1, -1, -1, 19, 19, 19, 19, 
	19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 
	19, 19, 19, 19, -1, 2, -1, 12
    };static const ANTLR3_INT32 dfa8_T3[] =
    {
	21
    };static const ANTLR3_INT32 dfa8_T4[] =
    {
	43
    };static const ANTLR3_INT32 dfa8_T5[] =
    {
	42
    };static const ANTLR3_INT32 dfa8_T6[] =
    {
	40
    };static const ANTLR3_INT32 dfa8_T7[] =
    {
	23
    };static const ANTLR3_INT32 dfa8_T8[] =
    {
	38
    };static const ANTLR3_INT32 dfa8_T9[] =
    {
	36
    };static const ANTLR3_INT32 dfa8_T10[] =
    {
	33
    };static const ANTLR3_INT32 dfa8_T11[] =
    {
	25
    };static const ANTLR3_INT32 dfa8_T12[] =
    {
	30, 31
    };static const ANTLR3_INT32 dfa8_T13[] =
    {
	19, 19, 19, 19, 19, 19, 19, 19, 19, 19, -1, -1, -1, -1, -1, -1, -1, 19, 
	19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 
	19, 19, 19, 19, 19, 19, 19, -1, -1, -1, -1, -1, -1, 19, 19, 19, 19, 19, 
	19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 
	19, 19, 19
    };static const ANTLR3_INT32 dfa8_T14[] =
    {
	41, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, 41, -1, -1, -1, -1, -1, -1, -1, 41
    };static const ANTLR3_INT32 dfa8_T15[] =
    {
	37
    };static const ANTLR3_INT32 dfa8_T16[] =
    {
	39
    };static const ANTLR3_INT32 dfa8_T17[] =
    {
	35
    };

/* Transition tables are a table of sub tables, with some tables
 * reused for efficiency.
 */
static const ANTLR3_INT32 * const dfa8_transitions[] =
{
    dfa8_T2, dfa8_T3, dfa8_T7, dfa8_T_empty, dfa8_T11, dfa8_T0, dfa8_T12, 
    dfa8_T_empty, dfa8_T_empty, dfa8_T_empty, dfa8_T_empty, dfa8_T_empty, 
    dfa8_T_empty, dfa8_T_empty, dfa8_T_empty, dfa8_T_empty, dfa8_T_empty, 
    dfa8_T10, dfa8_T1, dfa8_T_empty, dfa8_T_empty, dfa8_T_empty, dfa8_T_empty, 
    dfa8_T_empty, dfa8_T_empty, dfa8_T_empty, dfa8_T_empty, dfa8_T_empty, 
    dfa8_T_empty, dfa8_T_empty, dfa8_T_empty, dfa8_T_empty, dfa8_T_empty, 
    dfa8_T17, dfa8_T9, dfa8_T15, dfa8_T8, dfa8_T16, dfa8_T6, dfa8_T14, dfa8_T5, 
    dfa8_T_empty, dfa8_T4, dfa8_T13, dfa8_T_empty	
};


/* Declare tracking structure for Cyclic DFA 8
 */
static
ANTLR3_CYCLIC_DFA cdfa8
    =	{
	    8,		    /* Decision number of this dfa	    */
	    /* Which decision this represents:   */
	    (const pANTLR3_UCHAR)"1:1: Tokens : ( BOOL_AND | BOOL_OR | BIT_AND | BIT_OR | EQUAL | NOT_EQUAL | LESS_THAN | GREATER_THAN | EQUAL_OR_LESS_THAN | EQUAL_OR_GREATER_THAN | SHIFT_LEFT | SHIFT_RIGHT | PLUS | MINUS | MULT | DIV | MOD | BIT_NOT | BOOL_NOT | T__32 | T__33 | NUMBER | WHITESPACE | EXIST | DEFINED | IDENTIFIER | STRING );",	
	    (CDFA_SPECIAL_FUNC) antlr3dfaspecialStateTransition,	/* Default special state transition function	*/
	    antlr3dfaspecialTransition,		/* DFA specialTransition is currently just a default function in the runtime */
	    antlr3dfapredict,			/* DFA simulator function is in the runtime */
	    dfa8_eot,	    /* EOT table			    */
	    dfa8_eof,	    /* EOF table			    */
	    dfa8_min,	    /* Minimum tokens for each state    */
	    dfa8_max,	    /* Maximum tokens for each state    */
	    dfa8_accept,	/* Accept table			    */
	    dfa8_special,	/* Special transition states	    */
	    dfa8_transitions	/* Table of transition tables	    */

	};	    
/* End of Cyclic DFA 8
 * ---------------------
 */ 
/* =========================================================================
 * End of DFA tables for the lexer
 */ 

/* =========================================================================
 * Functions to match the lexer grammar defined tokens from the input stream
 */

//   Comes from: 7:10: ( '&&' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start BOOL_AND
 *
 * Looks to match the characters the constitute the token BOOL_AND
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mBOOL_AND(pNMakeExpressionLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = BOOL_AND;
       
    
    // NMakeExpression.g3pl:7:10: ( '&&' )
    // NMakeExpression.g3pl:7:12: '&&'
    {
        MATCHS(lit_1); 
        if  (HASEXCEPTION())
        {
            goto ruleBOOL_ANDEx;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleBOOL_ANDEx; /* Prevent compiler warnings */
    ruleBOOL_ANDEx: ;

}
// $ANTLR end BOOL_AND

//   Comes from: 8:9: ( '||' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start BOOL_OR
 *
 * Looks to match the characters the constitute the token BOOL_OR
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mBOOL_OR(pNMakeExpressionLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = BOOL_OR;
       
    
    // NMakeExpression.g3pl:8:9: ( '||' )
    // NMakeExpression.g3pl:8:11: '||'
    {
        MATCHS(lit_2); 
        if  (HASEXCEPTION())
        {
            goto ruleBOOL_OREx;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleBOOL_OREx; /* Prevent compiler warnings */
    ruleBOOL_OREx: ;

}
// $ANTLR end BOOL_OR

//   Comes from: 9:9: ( '&' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start BIT_AND
 *
 * Looks to match the characters the constitute the token BIT_AND
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mBIT_AND(pNMakeExpressionLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = BIT_AND;
       
    
    // NMakeExpression.g3pl:9:9: ( '&' )
    // NMakeExpression.g3pl:9:11: '&'
    {
        MATCHC('&'); 
        if  (HASEXCEPTION())
        {
            goto ruleBIT_ANDEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleBIT_ANDEx; /* Prevent compiler warnings */
    ruleBIT_ANDEx: ;

}
// $ANTLR end BIT_AND

//   Comes from: 10:8: ( '|' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start BIT_OR
 *
 * Looks to match the characters the constitute the token BIT_OR
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mBIT_OR(pNMakeExpressionLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = BIT_OR;
       
    
    // NMakeExpression.g3pl:10:8: ( '|' )
    // NMakeExpression.g3pl:10:10: '|'
    {
        MATCHC('|'); 
        if  (HASEXCEPTION())
        {
            goto ruleBIT_OREx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleBIT_OREx; /* Prevent compiler warnings */
    ruleBIT_OREx: ;

}
// $ANTLR end BIT_OR

//   Comes from: 11:7: ( '==' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start EQUAL
 *
 * Looks to match the characters the constitute the token EQUAL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mEQUAL(pNMakeExpressionLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = EQUAL;
       
    
    // NMakeExpression.g3pl:11:7: ( '==' )
    // NMakeExpression.g3pl:11:9: '=='
    {
        MATCHS(lit_3); 
        if  (HASEXCEPTION())
        {
            goto ruleEQUALEx;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleEQUALEx; /* Prevent compiler warnings */
    ruleEQUALEx: ;

}
// $ANTLR end EQUAL

//   Comes from: 12:11: ( '!=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start NOT_EQUAL
 *
 * Looks to match the characters the constitute the token NOT_EQUAL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mNOT_EQUAL(pNMakeExpressionLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = NOT_EQUAL;
       
    
    // NMakeExpression.g3pl:12:11: ( '!=' )
    // NMakeExpression.g3pl:12:13: '!='
    {
        MATCHS(lit_4); 
        if  (HASEXCEPTION())
        {
            goto ruleNOT_EQUALEx;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleNOT_EQUALEx; /* Prevent compiler warnings */
    ruleNOT_EQUALEx: ;

}
// $ANTLR end NOT_EQUAL

//   Comes from: 13:11: ( '<' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LESS_THAN
 *
 * Looks to match the characters the constitute the token LESS_THAN
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mLESS_THAN(pNMakeExpressionLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = LESS_THAN;
       
    
    // NMakeExpression.g3pl:13:11: ( '<' )
    // NMakeExpression.g3pl:13:13: '<'
    {
        MATCHC('<'); 
        if  (HASEXCEPTION())
        {
            goto ruleLESS_THANEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleLESS_THANEx; /* Prevent compiler warnings */
    ruleLESS_THANEx: ;

}
// $ANTLR end LESS_THAN

//   Comes from: 14:14: ( '>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start GREATER_THAN
 *
 * Looks to match the characters the constitute the token GREATER_THAN
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mGREATER_THAN(pNMakeExpressionLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = GREATER_THAN;
       
    
    // NMakeExpression.g3pl:14:14: ( '>' )
    // NMakeExpression.g3pl:14:16: '>'
    {
        MATCHC('>'); 
        if  (HASEXCEPTION())
        {
            goto ruleGREATER_THANEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleGREATER_THANEx; /* Prevent compiler warnings */
    ruleGREATER_THANEx: ;

}
// $ANTLR end GREATER_THAN

//   Comes from: 15:20: ( '<=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start EQUAL_OR_LESS_THAN
 *
 * Looks to match the characters the constitute the token EQUAL_OR_LESS_THAN
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mEQUAL_OR_LESS_THAN(pNMakeExpressionLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = EQUAL_OR_LESS_THAN;
       
    
    // NMakeExpression.g3pl:15:20: ( '<=' )
    // NMakeExpression.g3pl:15:22: '<='
    {
        MATCHS(lit_5); 
        if  (HASEXCEPTION())
        {
            goto ruleEQUAL_OR_LESS_THANEx;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleEQUAL_OR_LESS_THANEx; /* Prevent compiler warnings */
    ruleEQUAL_OR_LESS_THANEx: ;

}
// $ANTLR end EQUAL_OR_LESS_THAN

//   Comes from: 16:23: ( '>=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start EQUAL_OR_GREATER_THAN
 *
 * Looks to match the characters the constitute the token EQUAL_OR_GREATER_THAN
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mEQUAL_OR_GREATER_THAN(pNMakeExpressionLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = EQUAL_OR_GREATER_THAN;
       
    
    // NMakeExpression.g3pl:16:23: ( '>=' )
    // NMakeExpression.g3pl:16:25: '>='
    {
        MATCHS(lit_6); 
        if  (HASEXCEPTION())
        {
            goto ruleEQUAL_OR_GREATER_THANEx;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleEQUAL_OR_GREATER_THANEx; /* Prevent compiler warnings */
    ruleEQUAL_OR_GREATER_THANEx: ;

}
// $ANTLR end EQUAL_OR_GREATER_THAN

//   Comes from: 17:12: ( '<<' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start SHIFT_LEFT
 *
 * Looks to match the characters the constitute the token SHIFT_LEFT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSHIFT_LEFT(pNMakeExpressionLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = SHIFT_LEFT;
       
    
    // NMakeExpression.g3pl:17:12: ( '<<' )
    // NMakeExpression.g3pl:17:14: '<<'
    {
        MATCHS(lit_7); 
        if  (HASEXCEPTION())
        {
            goto ruleSHIFT_LEFTEx;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleSHIFT_LEFTEx; /* Prevent compiler warnings */
    ruleSHIFT_LEFTEx: ;

}
// $ANTLR end SHIFT_LEFT

//   Comes from: 18:13: ( '>>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start SHIFT_RIGHT
 *
 * Looks to match the characters the constitute the token SHIFT_RIGHT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSHIFT_RIGHT(pNMakeExpressionLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = SHIFT_RIGHT;
       
    
    // NMakeExpression.g3pl:18:13: ( '>>' )
    // NMakeExpression.g3pl:18:15: '>>'
    {
        MATCHS(lit_8); 
        if  (HASEXCEPTION())
        {
            goto ruleSHIFT_RIGHTEx;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleSHIFT_RIGHTEx; /* Prevent compiler warnings */
    ruleSHIFT_RIGHTEx: ;

}
// $ANTLR end SHIFT_RIGHT

//   Comes from: 19:6: ( '+' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start PLUS
 *
 * Looks to match the characters the constitute the token PLUS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mPLUS(pNMakeExpressionLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = PLUS;
       
    
    // NMakeExpression.g3pl:19:6: ( '+' )
    // NMakeExpression.g3pl:19:8: '+'
    {
        MATCHC('+'); 
        if  (HASEXCEPTION())
        {
            goto rulePLUSEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto rulePLUSEx; /* Prevent compiler warnings */
    rulePLUSEx: ;

}
// $ANTLR end PLUS

//   Comes from: 20:7: ( '-' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start MINUS
 *
 * Looks to match the characters the constitute the token MINUS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mMINUS(pNMakeExpressionLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = MINUS;
       
    
    // NMakeExpression.g3pl:20:7: ( '-' )
    // NMakeExpression.g3pl:20:9: '-'
    {
        MATCHC('-'); 
        if  (HASEXCEPTION())
        {
            goto ruleMINUSEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleMINUSEx; /* Prevent compiler warnings */
    ruleMINUSEx: ;

}
// $ANTLR end MINUS

//   Comes from: 21:6: ( '*' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start MULT
 *
 * Looks to match the characters the constitute the token MULT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mMULT(pNMakeExpressionLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = MULT;
       
    
    // NMakeExpression.g3pl:21:6: ( '*' )
    // NMakeExpression.g3pl:21:8: '*'
    {
        MATCHC('*'); 
        if  (HASEXCEPTION())
        {
            goto ruleMULTEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleMULTEx; /* Prevent compiler warnings */
    ruleMULTEx: ;

}
// $ANTLR end MULT

//   Comes from: 22:5: ( '/' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start DIV
 *
 * Looks to match the characters the constitute the token DIV
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mDIV(pNMakeExpressionLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = DIV;
       
    
    // NMakeExpression.g3pl:22:5: ( '/' )
    // NMakeExpression.g3pl:22:7: '/'
    {
        MATCHC('/'); 
        if  (HASEXCEPTION())
        {
            goto ruleDIVEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleDIVEx; /* Prevent compiler warnings */
    ruleDIVEx: ;

}
// $ANTLR end DIV

//   Comes from: 23:5: ( '%' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start MOD
 *
 * Looks to match the characters the constitute the token MOD
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mMOD(pNMakeExpressionLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = MOD;
       
    
    // NMakeExpression.g3pl:23:5: ( '%' )
    // NMakeExpression.g3pl:23:7: '%'
    {
        MATCHC('%'); 
        if  (HASEXCEPTION())
        {
            goto ruleMODEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleMODEx; /* Prevent compiler warnings */
    ruleMODEx: ;

}
// $ANTLR end MOD

//   Comes from: 24:9: ( '~' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start BIT_NOT
 *
 * Looks to match the characters the constitute the token BIT_NOT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mBIT_NOT(pNMakeExpressionLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = BIT_NOT;
       
    
    // NMakeExpression.g3pl:24:9: ( '~' )
    // NMakeExpression.g3pl:24:11: '~'
    {
        MATCHC('~'); 
        if  (HASEXCEPTION())
        {
            goto ruleBIT_NOTEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleBIT_NOTEx; /* Prevent compiler warnings */
    ruleBIT_NOTEx: ;

}
// $ANTLR end BIT_NOT

//   Comes from: 25:10: ( '!' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start BOOL_NOT
 *
 * Looks to match the characters the constitute the token BOOL_NOT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mBOOL_NOT(pNMakeExpressionLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = BOOL_NOT;
       
    
    // NMakeExpression.g3pl:25:10: ( '!' )
    // NMakeExpression.g3pl:25:12: '!'
    {
        MATCHC('!'); 
        if  (HASEXCEPTION())
        {
            goto ruleBOOL_NOTEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleBOOL_NOTEx; /* Prevent compiler warnings */
    ruleBOOL_NOTEx: ;

}
// $ANTLR end BOOL_NOT

//   Comes from: 26:7: ( '(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__32
 *
 * Looks to match the characters the constitute the token T__32
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__32(pNMakeExpressionLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = T__32;
       
    
    // NMakeExpression.g3pl:26:7: ( '(' )
    // NMakeExpression.g3pl:26:9: '('
    {
        MATCHC('('); 
        if  (HASEXCEPTION())
        {
            goto ruleT__32Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__32Ex; /* Prevent compiler warnings */
    ruleT__32Ex: ;

}
// $ANTLR end T__32

//   Comes from: 27:7: ( ')' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__33
 *
 * Looks to match the characters the constitute the token T__33
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__33(pNMakeExpressionLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = T__33;
       
    
    // NMakeExpression.g3pl:27:7: ( ')' )
    // NMakeExpression.g3pl:27:9: ')'
    {
        MATCHC(')'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__33Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__33Ex; /* Prevent compiler warnings */
    ruleT__33Ex: ;

}
// $ANTLR end T__33

//   Comes from: 248:17: ( ( DIGIT )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start NUMBER
 *
 * Looks to match the characters the constitute the token NUMBER
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mNUMBER(pNMakeExpressionLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = NUMBER;
       
    
    // NMakeExpression.g3pl:248:17: ( ( DIGIT )+ )
    // NMakeExpression.g3pl:248:19: ( DIGIT )+
    {
        // NMakeExpression.g3pl:248:19: ( DIGIT )+
        {
            int cnt1=0;

            for (;;)
            {
                int alt1=2;
        	{
        	   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
        	    */
        	    int LA1_0 = LA(1);
        	    if ( (((LA1_0 >= '0') && (LA1_0 <= '9'))) ) 
        	    {
        	        alt1=1;
        	    }

        	}
        	switch (alt1) 
        	{
        	    case 1:
        	        // NMakeExpression.g3pl:248:20: DIGIT
        	        {
        	            /* 248:20: DIGIT */
        	            mDIGIT(ctx ); 
        	            if  (HASEXCEPTION())
        	            {
        	                goto ruleNUMBEREx;
        	            }


        	        }
        	        break;

        	    default:
        	    
        		if ( cnt1 >= 1 )
        		{
        		    goto loop1;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleNUMBEREx;
        	}
        	cnt1++;
            }
            loop1: ;	/* Jump to here if this rule does not match */
        }

    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleNUMBEREx; /* Prevent compiler warnings */
    ruleNUMBEREx: ;

}
// $ANTLR end NUMBER

//   Comes from: 249:17: ( ( SPACE | '\\r' | '\\n' | '\\u000C' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start WHITESPACE
 *
 * Looks to match the characters the constitute the token WHITESPACE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mWHITESPACE(pNMakeExpressionLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = WHITESPACE;
       
    
    // NMakeExpression.g3pl:249:17: ( ( SPACE | '\\r' | '\\n' | '\\u000C' )+ )
    // NMakeExpression.g3pl:249:19: ( SPACE | '\\r' | '\\n' | '\\u000C' )+
    {
        // NMakeExpression.g3pl:249:19: ( SPACE | '\\r' | '\\n' | '\\u000C' )+
        {
            int cnt2=0;

            for (;;)
            {
                int alt2=2;
        	{
        	   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
        	    */
        	    int LA2_0 = LA(1);
        	    if ( (((LA2_0 >= '\t') && (LA2_0 <= '\n')) || ((LA2_0 >= '\f') && (LA2_0 <= '\r')) || LA2_0 == ' ') ) 
        	    {
        	        alt2=1;
        	    }

        	}
        	switch (alt2) 
        	{
        	    case 1:
        	        // NMakeExpression.g3pl:
        	        {
        	            if ( ((LA(1) >= '\t') && (LA(1) <= '\n')) || ((LA(1) >= '\f') && (LA(1) <= '\r')) || LA(1) == ' ' )
        	            {
        	                CONSUME();

        	            }
        	            else 
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();    goto ruleWHITESPACEEx;
        	            }


        	        }
        	        break;

        	    default:
        	    
        		if ( cnt2 >= 1 )
        		{
        		    goto loop2;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleWHITESPACEEx;
        	}
        	cnt2++;
            }
            loop2: ;	/* Jump to here if this rule does not match */
        }
        {
             LEXSTATE->channel = HIDDEN; 
        }

    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleWHITESPACEEx; /* Prevent compiler warnings */
    ruleWHITESPACEEx: ;

}
// $ANTLR end WHITESPACE

//   Comes from: 250:17: ( 'a' .. 'z' | 'A' .. 'Z' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LETTER
 *
 * Looks to match the characters the constitute the token LETTER
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mLETTER(pNMakeExpressionLexer ctx)
{
	ANTLR3_UINT32	_type;

        
    // NMakeExpression.g3pl:250:17: ( 'a' .. 'z' | 'A' .. 'Z' )
    // NMakeExpression.g3pl:
    {
        if ( ((LA(1) >= 'A') && (LA(1) <= 'Z')) || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        {
            CONSUME();

        }
        else 
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();    goto ruleLETTEREx;
        }


    }



    // This is where rules clean up and exit
    //
    goto ruleLETTEREx; /* Prevent compiler warnings */
    ruleLETTEREx: ;

}
// $ANTLR end LETTER

//   Comes from: 251:17: ( '0' .. '9' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start DIGIT
 *
 * Looks to match the characters the constitute the token DIGIT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mDIGIT(pNMakeExpressionLexer ctx)
{
	ANTLR3_UINT32	_type;

        
    // NMakeExpression.g3pl:251:17: ( '0' .. '9' )
    // NMakeExpression.g3pl:251:19: '0' .. '9'
    {
        MATCHRANGE('0', '9'); 
        if  (HASEXCEPTION())
        {
            goto ruleDIGITEx;
        }


    }



    // This is where rules clean up and exit
    //
    goto ruleDIGITEx; /* Prevent compiler warnings */
    ruleDIGITEx: ;

}
// $ANTLR end DIGIT

//   Comes from: 252:17: ( '\\t' | ' ' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start SPACE
 *
 * Looks to match the characters the constitute the token SPACE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSPACE(pNMakeExpressionLexer ctx)
{
	ANTLR3_UINT32	_type;

        
    // NMakeExpression.g3pl:252:17: ( '\\t' | ' ' )
    // NMakeExpression.g3pl:
    {
        if ( LA(1) == '\t' || LA(1) == ' ' )
        {
            CONSUME();

        }
        else 
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();    goto ruleSPACEEx;
        }


    }



    // This is where rules clean up and exit
    //
    goto ruleSPACEEx; /* Prevent compiler warnings */
    ruleSPACEEx: ;

}
// $ANTLR end SPACE

//   Comes from: 253:17: ( 'EXIST' ( SPACE )* '(' (~ ')' )+ ')' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start EXIST
 *
 * Looks to match the characters the constitute the token EXIST
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mEXIST(pNMakeExpressionLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = EXIST;
       
    
    // NMakeExpression.g3pl:253:17: ( 'EXIST' ( SPACE )* '(' (~ ')' )+ ')' )
    // NMakeExpression.g3pl:253:19: 'EXIST' ( SPACE )* '(' (~ ')' )+ ')'
    {
        MATCHS(lit_9); 
        if  (HASEXCEPTION())
        {
            goto ruleEXISTEx;
        }



        // NMakeExpression.g3pl:253:27: ( SPACE )*

        for (;;)
        {
            int alt3=2;
            {
               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                */
                int LA3_0 = LA(1);
                if ( (LA3_0 == '\t' || LA3_0 == ' ') ) 
                {
                    alt3=1;
                }

            }
            switch (alt3) 
            {
        	case 1:
        	    // NMakeExpression.g3pl:253:27: SPACE
        	    {
        	        /* 253:27: SPACE */
        	        mSPACE(ctx ); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleEXISTEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop3;	/* break out of the loop */
        	    break;
            }
        }
        loop3: ; /* Jump out to here if this rule does not match */

        MATCHC('('); 
        if  (HASEXCEPTION())
        {
            goto ruleEXISTEx;
        }

        // NMakeExpression.g3pl:253:38: (~ ')' )+
        {
            int cnt4=0;

            for (;;)
            {
                int alt4=2;
        	{
        	   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
        	    */
        	    int LA4_0 = LA(1);
        	    if ( (((LA4_0 >= 0x0000) && (LA4_0 <= '(')) || ((LA4_0 >= '*') && (LA4_0 <= 0xFFFF))) ) 
        	    {
        	        alt4=1;
        	    }

        	}
        	switch (alt4) 
        	{
        	    case 1:
        	        // NMakeExpression.g3pl:253:40: ~ ')'
        	        {
        	            if ( ((LA(1) >= 0x0000) && (LA(1) <= '(')) || ((LA(1) >= '*') && (LA(1) <= 0xFFFF)) )
        	            {
        	                CONSUME();

        	            }
        	            else 
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();    goto ruleEXISTEx;
        	            }


        	        }
        	        break;

        	    default:
        	    
        		if ( cnt4 >= 1 )
        		{
        		    goto loop4;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleEXISTEx;
        	}
        	cnt4++;
            }
            loop4: ;	/* Jump to here if this rule does not match */
        }
        MATCHC(')'); 
        if  (HASEXCEPTION())
        {
            goto ruleEXISTEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleEXISTEx; /* Prevent compiler warnings */
    ruleEXISTEx: ;

}
// $ANTLR end EXIST

//   Comes from: 254:17: ( 'DEFINED' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start DEFINED
 *
 * Looks to match the characters the constitute the token DEFINED
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mDEFINED(pNMakeExpressionLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = DEFINED;
       
    
    // NMakeExpression.g3pl:254:17: ( 'DEFINED' )
    // NMakeExpression.g3pl:254:19: 'DEFINED'
    {
        MATCHS(lit_10); 
        if  (HASEXCEPTION())
        {
            goto ruleDEFINEDEx;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleDEFINEDEx; /* Prevent compiler warnings */
    ruleDEFINEDEx: ;

}
// $ANTLR end DEFINED

//   Comes from: 255:17: ( LETTER ( LETTER | DIGIT )* )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start IDENTIFIER
 *
 * Looks to match the characters the constitute the token IDENTIFIER
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mIDENTIFIER(pNMakeExpressionLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = IDENTIFIER;
       
    
    // NMakeExpression.g3pl:255:17: ( LETTER ( LETTER | DIGIT )* )
    // NMakeExpression.g3pl:255:19: LETTER ( LETTER | DIGIT )*
    {
        /* 255:19: LETTER ( LETTER | DIGIT )* */
        mLETTER(ctx ); 
        if  (HASEXCEPTION())
        {
            goto ruleIDENTIFIEREx;
        }


        // NMakeExpression.g3pl:255:26: ( LETTER | DIGIT )*

        for (;;)
        {
            int alt5=2;
            {
               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                */
                int LA5_0 = LA(1);
                if ( (((LA5_0 >= '0') && (LA5_0 <= '9')) || ((LA5_0 >= 'A') && (LA5_0 <= 'Z')) || ((LA5_0 >= 'a') && (LA5_0 <= 'z'))) ) 
                {
                    alt5=1;
                }

            }
            switch (alt5) 
            {
        	case 1:
        	    // NMakeExpression.g3pl:
        	    {
        	        if ( ((LA(1) >= '0') && (LA(1) <= '9')) || ((LA(1) >= 'A') && (LA(1) <= 'Z')) || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        	        {
        	            CONSUME();

        	        }
        	        else 
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();    goto ruleIDENTIFIEREx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop5;	/* break out of the loop */
        	    break;
            }
        }
        loop5: ; /* Jump out to here if this rule does not match */


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleIDENTIFIEREx; /* Prevent compiler warnings */
    ruleIDENTIFIEREx: ;

}
// $ANTLR end IDENTIFIER

//   Comes from: 256:17: ( ( '\"' (~ '\"' )* '\"' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start STRING
 *
 * Looks to match the characters the constitute the token STRING
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSTRING(pNMakeExpressionLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = STRING;
       
    
    // NMakeExpression.g3pl:256:17: ( ( '\"' (~ '\"' )* '\"' )+ )
    // NMakeExpression.g3pl:256:19: ( '\"' (~ '\"' )* '\"' )+
    {
        // NMakeExpression.g3pl:256:19: ( '\"' (~ '\"' )* '\"' )+
        {
            int cnt7=0;

            for (;;)
            {
                int alt7=2;
        	{
        	   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
        	    */
        	    int LA7_0 = LA(1);
        	    if ( (LA7_0 == '"') ) 
        	    {
        	        alt7=1;
        	    }

        	}
        	switch (alt7) 
        	{
        	    case 1:
        	        // NMakeExpression.g3pl:256:20: '\"' (~ '\"' )* '\"'
        	        {
        	            MATCHC('"'); 
        	            if  (HASEXCEPTION())
        	            {
        	                goto ruleSTRINGEx;
        	            }


        	            // NMakeExpression.g3pl:256:24: (~ '\"' )*

        	            for (;;)
        	            {
        	                int alt6=2;
        	                {
        	                   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
        	                    */
        	                    int LA6_0 = LA(1);
        	                    if ( (((LA6_0 >= 0x0000) && (LA6_0 <= '!')) || ((LA6_0 >= '#') && (LA6_0 <= 0xFFFF))) ) 
        	                    {
        	                        alt6=1;
        	                    }

        	                }
        	                switch (alt6) 
        	                {
        	            	case 1:
        	            	    // NMakeExpression.g3pl:256:25: ~ '\"'
        	            	    {
        	            	        if ( ((LA(1) >= 0x0000) && (LA(1) <= '!')) || ((LA(1) >= '#') && (LA(1) <= 0xFFFF)) )
        	            	        {
        	            	            CONSUME();

        	            	        }
        	            	        else 
        	            	        {
        	            	            CONSTRUCTEX();
        	            	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            	            LRECOVER();    goto ruleSTRINGEx;
        	            	        }


        	            	    }
        	            	    break;

        	            	default:
        	            	    goto loop6;	/* break out of the loop */
        	            	    break;
        	                }
        	            }
        	            loop6: ; /* Jump out to here if this rule does not match */

        	            MATCHC('"'); 
        	            if  (HASEXCEPTION())
        	            {
        	                goto ruleSTRINGEx;
        	            }


        	        }
        	        break;

        	    default:
        	    
        		if ( cnt7 >= 1 )
        		{
        		    goto loop7;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleSTRINGEx;
        	}
        	cnt7++;
            }
            loop7: ;	/* Jump to here if this rule does not match */
        }

    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleSTRINGEx; /* Prevent compiler warnings */
    ruleSTRINGEx: ;

}
// $ANTLR end STRING

/** This is the entry point in to the lexer from an object that
 *  wants to generate the next token, such as a pCOMMON_TOKEN_STREAM
 */
static void 
mTokens(pNMakeExpressionLexer ctx)
{
    {
        //  NMakeExpression.g3pl:1:8: ( BOOL_AND | BOOL_OR | BIT_AND | BIT_OR | EQUAL | NOT_EQUAL | LESS_THAN | GREATER_THAN | EQUAL_OR_LESS_THAN | EQUAL_OR_GREATER_THAN | SHIFT_LEFT | SHIFT_RIGHT | PLUS | MINUS | MULT | DIV | MOD | BIT_NOT | BOOL_NOT | T__32 | T__33 | NUMBER | WHITESPACE | EXIST | DEFINED | IDENTIFIER | STRING )
        
        ANTLR3_UINT32 alt8;

        alt8=27;

        alt8 = cdfa8.predict(ctx, RECOGNIZER, ISTREAM, &cdfa8);
        if  (HASEXCEPTION())
        {
            goto ruleTokensEx;
        }

        switch (alt8) 
        {
    	case 1:
    	    // NMakeExpression.g3pl:1:10: BOOL_AND
    	    {
    	        /* 1:10: BOOL_AND */
    	        mBOOL_AND(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 2:
    	    // NMakeExpression.g3pl:1:19: BOOL_OR
    	    {
    	        /* 1:19: BOOL_OR */
    	        mBOOL_OR(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 3:
    	    // NMakeExpression.g3pl:1:27: BIT_AND
    	    {
    	        /* 1:27: BIT_AND */
    	        mBIT_AND(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 4:
    	    // NMakeExpression.g3pl:1:35: BIT_OR
    	    {
    	        /* 1:35: BIT_OR */
    	        mBIT_OR(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 5:
    	    // NMakeExpression.g3pl:1:42: EQUAL
    	    {
    	        /* 1:42: EQUAL */
    	        mEQUAL(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 6:
    	    // NMakeExpression.g3pl:1:48: NOT_EQUAL
    	    {
    	        /* 1:48: NOT_EQUAL */
    	        mNOT_EQUAL(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 7:
    	    // NMakeExpression.g3pl:1:58: LESS_THAN
    	    {
    	        /* 1:58: LESS_THAN */
    	        mLESS_THAN(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 8:
    	    // NMakeExpression.g3pl:1:68: GREATER_THAN
    	    {
    	        /* 1:68: GREATER_THAN */
    	        mGREATER_THAN(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 9:
    	    // NMakeExpression.g3pl:1:81: EQUAL_OR_LESS_THAN
    	    {
    	        /* 1:81: EQUAL_OR_LESS_THAN */
    	        mEQUAL_OR_LESS_THAN(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 10:
    	    // NMakeExpression.g3pl:1:100: EQUAL_OR_GREATER_THAN
    	    {
    	        /* 1:100: EQUAL_OR_GREATER_THAN */
    	        mEQUAL_OR_GREATER_THAN(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 11:
    	    // NMakeExpression.g3pl:1:122: SHIFT_LEFT
    	    {
    	        /* 1:122: SHIFT_LEFT */
    	        mSHIFT_LEFT(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 12:
    	    // NMakeExpression.g3pl:1:133: SHIFT_RIGHT
    	    {
    	        /* 1:133: SHIFT_RIGHT */
    	        mSHIFT_RIGHT(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 13:
    	    // NMakeExpression.g3pl:1:145: PLUS
    	    {
    	        /* 1:145: PLUS */
    	        mPLUS(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 14:
    	    // NMakeExpression.g3pl:1:150: MINUS
    	    {
    	        /* 1:150: MINUS */
    	        mMINUS(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 15:
    	    // NMakeExpression.g3pl:1:156: MULT
    	    {
    	        /* 1:156: MULT */
    	        mMULT(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 16:
    	    // NMakeExpression.g3pl:1:161: DIV
    	    {
    	        /* 1:161: DIV */
    	        mDIV(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 17:
    	    // NMakeExpression.g3pl:1:165: MOD
    	    {
    	        /* 1:165: MOD */
    	        mMOD(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 18:
    	    // NMakeExpression.g3pl:1:169: BIT_NOT
    	    {
    	        /* 1:169: BIT_NOT */
    	        mBIT_NOT(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 19:
    	    // NMakeExpression.g3pl:1:177: BOOL_NOT
    	    {
    	        /* 1:177: BOOL_NOT */
    	        mBOOL_NOT(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 20:
    	    // NMakeExpression.g3pl:1:186: T__32
    	    {
    	        /* 1:186: T__32 */
    	        mT__32(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 21:
    	    // NMakeExpression.g3pl:1:192: T__33
    	    {
    	        /* 1:192: T__33 */
    	        mT__33(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 22:
    	    // NMakeExpression.g3pl:1:198: NUMBER
    	    {
    	        /* 1:198: NUMBER */
    	        mNUMBER(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 23:
    	    // NMakeExpression.g3pl:1:205: WHITESPACE
    	    {
    	        /* 1:205: WHITESPACE */
    	        mWHITESPACE(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 24:
    	    // NMakeExpression.g3pl:1:216: EXIST
    	    {
    	        /* 1:216: EXIST */
    	        mEXIST(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 25:
    	    // NMakeExpression.g3pl:1:222: DEFINED
    	    {
    	        /* 1:222: DEFINED */
    	        mDEFINED(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 26:
    	    // NMakeExpression.g3pl:1:230: IDENTIFIER
    	    {
    	        /* 1:230: IDENTIFIER */
    	        mIDENTIFIER(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 27:
    	    // NMakeExpression.g3pl:1:241: STRING
    	    {
    	        /* 1:241: STRING */
    	        mSTRING(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;

        }
    }

    
    goto ruleTokensEx; /* Prevent compiler warnings */
ruleTokensEx: ;
}

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */
/* End of Lexer code
 * ================================================
 * ================================================
 */ 


/* End of code
 * =============================================================================
 */
