/** \file
 *  This C source file was generated by $ANTLR version 3.1.1
 *
 *     -  From the grammar source file : NMakeExpression.g3pl
 *     -                            On : 2009-01-28 18:57:13
 *     -                for the parser : NMakeExpressionParserParser *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/

/* =============================================================================
 * This is what the grammar programmer asked us to put at the top of every file.
 */


/* End of Header action.
 * =============================================================================
 */
/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "NMakeExpressionParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */
 
#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pNMakeExpressionParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  pNMakeExpressionParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pNMakeExpressionParser_##scope##Top
#define	SCOPE_SIZE(scope)			(ctx->SCOPE_STACK(scope)->size(ctx->SCOPE_STACK(scope)))
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */
 
#undef	    PARSER		    
#undef	    RECOGNIZER		    
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO		    
#undef		DBG

#define	    PARSER							ctx->pParser  
#define	    RECOGNIZER						PARSER->rec
#define		PSRSTATE						RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)				RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		MEMOIZE(ri,si)					RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT							PARSER->tstream
#define	    STRSTREAM						INPUT
#define		ISTREAM							INPUT->istream
#define		INDEX()							ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()					(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION						PSRSTATE->exception
#define	    MATCHT(t, fs)					RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()						RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK					    PSRSTATE->following
#define	    FOLLOWPUSH(x)					FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()						FOLLOWSTACK->pop(FOLLOWSTACK)
#define	    PRECOVER()						RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()					RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)							INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)							INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()					RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()						ISTREAM->consume(ISTREAM)
#define	    MARK()							ISTREAM->mark(ISTREAM)
#define	    REWIND(m)						ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()					ISTREAM->rewindLast(ISTREAM)
#define		SEEK(n)							ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY					PSRSTATE->errorRecovery
#define	    FAILEDFLAG						PSRSTATE->failed
#define	    HASFAILED()						(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING					PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger

#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */



/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   NMakeExpressionParserTokenNames[30+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>", 
        (pANTLR3_UINT8) "<UP>", 
        (pANTLR3_UINT8) "BOOL_AND",
        (pANTLR3_UINT8) "BOOL_OR",
        (pANTLR3_UINT8) "BIT_AND",
        (pANTLR3_UINT8) "BIT_OR",
        (pANTLR3_UINT8) "EQUAL",
        (pANTLR3_UINT8) "NOT_EQUAL",
        (pANTLR3_UINT8) "LESS_THAN",
        (pANTLR3_UINT8) "GREATER_THAN",
        (pANTLR3_UINT8) "EQUAL_OR_LESS_THAN",
        (pANTLR3_UINT8) "EQUAL_OR_GREATER_THAN",
        (pANTLR3_UINT8) "SHIFT_LEFT",
        (pANTLR3_UINT8) "SHIFT_RIGHT",
        (pANTLR3_UINT8) "PLUS",
        (pANTLR3_UINT8) "MINUS",
        (pANTLR3_UINT8) "MULT",
        (pANTLR3_UINT8) "DIV",
        (pANTLR3_UINT8) "MOD",
        (pANTLR3_UINT8) "BIT_NOT",
        (pANTLR3_UINT8) "BOOL_NOT",
        (pANTLR3_UINT8) "STRING",
        (pANTLR3_UINT8) "NUMBER",
        (pANTLR3_UINT8) "DEFINED",
        (pANTLR3_UINT8) "IDENTIFIER",
        (pANTLR3_UINT8) "EXIST",
        (pANTLR3_UINT8) "DIGIT",
        (pANTLR3_UINT8) "SPACE",
        (pANTLR3_UINT8) "WHITESPACE",
        (pANTLR3_UINT8) "LETTER",
        (pANTLR3_UINT8) "'('",
        (pANTLR3_UINT8) "')'"
       };

        

// Forward declare the locally static matching functions we have generated.
//
static int	expr    (pNMakeExpressionParser ctx, void* caller, void* cbIsMacroDefined, void* cbFileExisting);
static int	term0    (pNMakeExpressionParser ctx);
static int	term1    (pNMakeExpressionParser ctx);
static int	term2    (pNMakeExpressionParser ctx);
static int	term3    (pNMakeExpressionParser ctx);
static int	term4    (pNMakeExpressionParser ctx);
static int	term5    (pNMakeExpressionParser ctx);
static int	primary    (pNMakeExpressionParser ctx);
static void	NMakeExpressionParserFree(pNMakeExpressionParser ctx);
/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed. 
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "NMakeExpression.g3pl";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new NMakeExpressionParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pNMakeExpressionParser
NMakeExpressionParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return NMakeExpressionParserNewSSD(instream, NULL);
}

/** \brief Create a new NMakeExpressionParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pNMakeExpressionParser
NMakeExpressionParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pNMakeExpressionParser ctx;	    /* Context structure we will build and return   */
    
    ctx	= (pNMakeExpressionParser) ANTLR3_CALLOC(1, sizeof(NMakeExpressionParser));
    
    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }
    
    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function. 
     *
     * We don't use the macros defined in NMakeExpressionParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our NMakeExpressionParser interface
     */
    ctx->expr	= expr;
    ctx->term0	= term0;
    ctx->term1	= term1;
    ctx->term2	= term2;
    ctx->term3	= term3;
    ctx->term4	= term4;
    ctx->term5	= term5;
    ctx->primary	= primary;
    ctx->free			= NMakeExpressionParserFree;
    ctx->getGrammarFileName	= getGrammarFileName;
    
    /* Install the scope pushing methods.
     */

        
    

	
    /* Install the token table
     */
    PSRSTATE->tokenNames   = NMakeExpressionParserTokenNames;
    
    
    /* Return the newly built parser to the caller
     */
    return  ctx;
}

/** Free the parser resources
 */
 static void
 NMakeExpressionParserFree(pNMakeExpressionParser ctx)
 {
    /* Free any scope memory
     */
    
        
	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);
    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }
 
/** Return token names used by this parser
 *
 * The returned pointer is used as an index into the token names table (using the token 
 * number as the index).
 * 
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames() 
{
        return NMakeExpressionParserTokenNames; 
}


        typedef int (*stringCallback)(void*, pANTLR3_STRING);
        void* _caller;
        stringCallback _isMacroDefined;
        stringCallback _isFileExisting;
        
        static int isMacroDefined(pANTLR3_STRING macro)
        {
            return ((stringCallback)(_isMacroDefined))(_caller, macro);
        }
        
        static int isFileExisting(pANTLR3_STRING filename)
        {
            return ((stringCallback)(_isFileExisting))(_caller, filename);
        }

    
/* Declare the bitsets
 */

/** Bitset defining follow set for error recovery in rule state: FOLLOW_term0_in_expr304  */
static	ANTLR3_BITWORD FOLLOW_term0_in_expr304_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_term0_in_expr304	= { FOLLOW_term0_in_expr304_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_STRING_in_expr322  */
static	ANTLR3_BITWORD FOLLOW_STRING_in_expr322_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000300) };
static  ANTLR3_BITSET_LIST FOLLOW_STRING_in_expr322	= { FOLLOW_STRING_in_expr322_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_expr326  */
static	ANTLR3_BITWORD FOLLOW_set_in_expr326_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000800000) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_expr326	= { FOLLOW_set_in_expr326_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_STRING_in_expr336  */
static	ANTLR3_BITWORD FOLLOW_STRING_in_expr336_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_STRING_in_expr336	= { FOLLOW_STRING_in_expr336_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_term1_in_term0369  */
static	ANTLR3_BITWORD FOLLOW_term1_in_term0369_bits[]	= { ANTLR3_UINT64_LIT(0x00000000000000F2) };
static  ANTLR3_BITSET_LIST FOLLOW_term1_in_term0369	= { FOLLOW_term1_in_term0369_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_term0389  */
static	ANTLR3_BITWORD FOLLOW_set_in_term0389_bits[]	= { ANTLR3_UINT64_LIT(0x000000010B620000) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_term0389	= { FOLLOW_set_in_term0389_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_term1_in_term0408  */
static	ANTLR3_BITWORD FOLLOW_term1_in_term0408_bits[]	= { ANTLR3_UINT64_LIT(0x00000000000000F2) };
static  ANTLR3_BITSET_LIST FOLLOW_term1_in_term0408	= { FOLLOW_term1_in_term0408_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_term2_in_term1446  */
static	ANTLR3_BITWORD FOLLOW_term2_in_term1446_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000003F02) };
static  ANTLR3_BITSET_LIST FOLLOW_term2_in_term1446	= { FOLLOW_term2_in_term1446_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_term1466  */
static	ANTLR3_BITWORD FOLLOW_set_in_term1466_bits[]	= { ANTLR3_UINT64_LIT(0x000000010B620000) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_term1466	= { FOLLOW_set_in_term1466_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_term2_in_term1492  */
static	ANTLR3_BITWORD FOLLOW_term2_in_term1492_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000003F02) };
static  ANTLR3_BITSET_LIST FOLLOW_term2_in_term1492	= { FOLLOW_term2_in_term1492_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_term3_in_term2532  */
static	ANTLR3_BITWORD FOLLOW_term3_in_term2532_bits[]	= { ANTLR3_UINT64_LIT(0x000000000000C002) };
static  ANTLR3_BITSET_LIST FOLLOW_term3_in_term2532	= { FOLLOW_term3_in_term2532_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_term2552  */
static	ANTLR3_BITWORD FOLLOW_set_in_term2552_bits[]	= { ANTLR3_UINT64_LIT(0x000000010B620000) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_term2552	= { FOLLOW_set_in_term2552_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_term3_in_term2562  */
static	ANTLR3_BITWORD FOLLOW_term3_in_term2562_bits[]	= { ANTLR3_UINT64_LIT(0x000000000000C002) };
static  ANTLR3_BITSET_LIST FOLLOW_term3_in_term2562	= { FOLLOW_term3_in_term2562_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_term4_in_term3601  */
static	ANTLR3_BITWORD FOLLOW_term4_in_term3601_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000030002) };
static  ANTLR3_BITSET_LIST FOLLOW_term4_in_term3601	= { FOLLOW_term4_in_term3601_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_term3621  */
static	ANTLR3_BITWORD FOLLOW_set_in_term3621_bits[]	= { ANTLR3_UINT64_LIT(0x000000010B620000) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_term3621	= { FOLLOW_set_in_term3621_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_term4_in_term3631  */
static	ANTLR3_BITWORD FOLLOW_term4_in_term3631_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000030002) };
static  ANTLR3_BITSET_LIST FOLLOW_term4_in_term3631	= { FOLLOW_term4_in_term3631_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_term5_in_term4670  */
static	ANTLR3_BITWORD FOLLOW_term5_in_term4670_bits[]	= { ANTLR3_UINT64_LIT(0x00000000001C0002) };
static  ANTLR3_BITSET_LIST FOLLOW_term5_in_term4670	= { FOLLOW_term5_in_term4670_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_term4690  */
static	ANTLR3_BITWORD FOLLOW_set_in_term4690_bits[]	= { ANTLR3_UINT64_LIT(0x000000010B620000) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_term4690	= { FOLLOW_set_in_term4690_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_term5_in_term4704  */
static	ANTLR3_BITWORD FOLLOW_term5_in_term4704_bits[]	= { ANTLR3_UINT64_LIT(0x00000000001C0002) };
static  ANTLR3_BITSET_LIST FOLLOW_term5_in_term4704	= { FOLLOW_term5_in_term4704_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_term5743  */
static	ANTLR3_BITWORD FOLLOW_set_in_term5743_bits[]	= { ANTLR3_UINT64_LIT(0x000000010B620000) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_term5743	= { FOLLOW_set_in_term5743_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_primary_in_term5758  */
static	ANTLR3_BITWORD FOLLOW_primary_in_term5758_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_primary_in_term5758	= { FOLLOW_primary_in_term5758_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NUMBER_in_primary790  */
static	ANTLR3_BITWORD FOLLOW_NUMBER_in_primary790_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NUMBER_in_primary790	= { FOLLOW_NUMBER_in_primary790_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_DEFINED_in_primary806  */
static	ANTLR3_BITWORD FOLLOW_DEFINED_in_primary806_bits[]	= { ANTLR3_UINT64_LIT(0x0000000100000000) };
static  ANTLR3_BITSET_LIST FOLLOW_DEFINED_in_primary806	= { FOLLOW_DEFINED_in_primary806_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_32_in_primary808  */
static	ANTLR3_BITWORD FOLLOW_32_in_primary808_bits[]	= { ANTLR3_UINT64_LIT(0x0000000004800000) };
static  ANTLR3_BITSET_LIST FOLLOW_32_in_primary808	= { FOLLOW_32_in_primary808_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_primary812  */
static	ANTLR3_BITWORD FOLLOW_set_in_primary812_bits[]	= { ANTLR3_UINT64_LIT(0x0000000200000000) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_primary812	= { FOLLOW_set_in_primary812_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_33_in_primary820  */
static	ANTLR3_BITWORD FOLLOW_33_in_primary820_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_33_in_primary820	= { FOLLOW_33_in_primary820_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_EXIST_in_primary838  */
static	ANTLR3_BITWORD FOLLOW_EXIST_in_primary838_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_EXIST_in_primary838	= { FOLLOW_EXIST_in_primary838_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_32_in_primary854  */
static	ANTLR3_BITWORD FOLLOW_32_in_primary854_bits[]	= { ANTLR3_UINT64_LIT(0x000000010B620000) };
static  ANTLR3_BITSET_LIST FOLLOW_32_in_primary854	= { FOLLOW_32_in_primary854_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_term0_in_primary858  */
static	ANTLR3_BITWORD FOLLOW_term0_in_primary858_bits[]	= { ANTLR3_UINT64_LIT(0x0000000200000000) };
static  ANTLR3_BITSET_LIST FOLLOW_term0_in_primary858	= { FOLLOW_term0_in_primary858_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_33_in_primary860  */
static	ANTLR3_BITWORD FOLLOW_33_in_primary860_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_33_in_primary860	= { FOLLOW_33_in_primary860_bits, 1	};
     

 
 
/* ==============================================
 * Parsing rules
 */
/** 
 * $ANTLR start expr
 * NMakeExpression.g3pl:53:1: expr[void* caller, void* cbIsMacroDefined, void* cbFileExisting] returns [int result] : (value= term0 | lhs= STRING op= ( EQUAL | NOT_EQUAL ) rhs= STRING );
 */
static int
expr(pNMakeExpressionParser ctx, void* caller, void* cbIsMacroDefined, void* cbFileExisting)
{   
    int result = 0;

    pANTLR3_COMMON_TOKEN    lhs;
    pANTLR3_COMMON_TOKEN    op;
    pANTLR3_COMMON_TOKEN    rhs;
    int value;
    #undef	RETURN_TYPE_value
    #define	RETURN_TYPE_value int

    /* Initialize rule variables
     */


    lhs       = NULL;
    op       = NULL;
    rhs       = NULL;
    value = 0;

    {
        {
            //  NMakeExpression.g3pl:54:22: (value= term0 | lhs= STRING op= ( EQUAL | NOT_EQUAL ) rhs= STRING )
            
            ANTLR3_UINT32 alt1;

            alt1=2;


            {
                int LA1_0 = LA(1);
                if ( (LA1_0 == MINUS || ((LA1_0 >= BIT_NOT) && (LA1_0 <= BOOL_NOT)) || ((LA1_0 >= NUMBER) && (LA1_0 <= DEFINED)) || LA1_0 == EXIST || LA1_0 == 32) ) 
                {
                    alt1=1;
                }
                else if ( (LA1_0 == STRING) ) 
                {
                    alt1=2;
                }
                else 
                {
                
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 1;
                    EXCEPTION->state        = 0;


                    goto ruleexprEx;
                }
            }
            switch (alt1) 
            {
        	case 1:
        	    // NMakeExpression.g3pl:55:9: value= term0
        	    {
        	        {

        	                        _caller = caller;
        	                        _isMacroDefined = cbIsMacroDefined;
        	                        _isFileExisting = cbFileExisting;
        	                    
        	        }
        	        FOLLOWPUSH(FOLLOW_term0_in_expr304);
        	        value=term0(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }

        	        {

        	                        result = value;
        	                    
        	        }

        	    }
        	    break;
        	case 2:
        	    // NMakeExpression.g3pl:64:5: lhs= STRING op= ( EQUAL | NOT_EQUAL ) rhs= STRING
        	    {
        	        lhs = (pANTLR3_COMMON_TOKEN) MATCHT(STRING, &FOLLOW_STRING_in_expr322); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }

        	        op=(pANTLR3_COMMON_TOKEN)LT(1);
        	        if ( ((LA(1) >= EQUAL) && (LA(1) <= NOT_EQUAL)) )
        	        {
        	            CONSUME();
        	            PERRORRECOVERY=ANTLR3_FALSE;
        	        }
        	        else 
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
        	            EXCEPTION->expectingSet = &FOLLOW_set_in_expr326;
        	            RECOVERFROMMISMATCHEDSET(&FOLLOW_set_in_expr326);    goto ruleexprEx;
        	        }

        	        rhs = (pANTLR3_COMMON_TOKEN) MATCHT(STRING, &FOLLOW_STRING_in_expr336); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }

        	        {

        	                        pANTLR3_STRING s1 = lhs->getText(lhs);
        	                        pANTLR3_STRING s2 = rhs->getText(rhs);
        	                        ANTLR3_UINT32 cmp = s1->compareS(s1, s2);
        	                        switch (op->getType(op))
        	                        {
        	                            case EQUAL:
        	                                result = (cmp == 0);
        	                                break;
        	                            case NOT_EQUAL:
        	                                result = (cmp != 0);
        	                                break;
        	                        }
        	                    
        	        }

        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto ruleexprEx; /* Prevent compiler warnings */
    ruleexprEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return result;
}
/* $ANTLR end expr */

/** 
 * $ANTLR start term0
 * NMakeExpression.g3pl:81:1: term0 returns [int result] : lhs= term1 (op= ( BOOL_AND | BOOL_OR | BIT_AND | BIT_OR ) rhs= term1 )* ;
 */
static int
term0(pNMakeExpressionParser ctx)
{   
    int result = 0;

    pANTLR3_COMMON_TOKEN    op;
    int lhs;
    #undef	RETURN_TYPE_lhs
    #define	RETURN_TYPE_lhs int

    int rhs;
    #undef	RETURN_TYPE_rhs
    #define	RETURN_TYPE_rhs int

    /* Initialize rule variables
     */


    op       = NULL;
    lhs = 0;
    rhs = 0;

    {
        // NMakeExpression.g3pl:81:28: (lhs= term1 (op= ( BOOL_AND | BOOL_OR | BIT_AND | BIT_OR ) rhs= term1 )* )
        // NMakeExpression.g3pl:82:5: lhs= term1 (op= ( BOOL_AND | BOOL_OR | BIT_AND | BIT_OR ) rhs= term1 )*
        {
            FOLLOWPUSH(FOLLOW_term1_in_term0369);
            lhs=term1(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleterm0Ex;
            }

            {

                            result = lhs;
                        
            }

            // NMakeExpression.g3pl:86:5: (op= ( BOOL_AND | BOOL_OR | BIT_AND | BIT_OR ) rhs= term1 )*

            for (;;)
            {
                int alt2=2;
                {
                   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                    */
                    int LA2_0 = LA(1);
                    if ( (((LA2_0 >= BOOL_AND) && (LA2_0 <= BIT_OR))) ) 
                    {
                        alt2=1;
                    }

                }
                switch (alt2) 
                {
            	case 1:
            	    // NMakeExpression.g3pl:86:7: op= ( BOOL_AND | BOOL_OR | BIT_AND | BIT_OR ) rhs= term1
            	    {
            	        op=(pANTLR3_COMMON_TOKEN)LT(1);
            	        if ( ((LA(1) >= BOOL_AND) && (LA(1) <= BIT_OR)) )
            	        {
            	            CONSUME();
            	            PERRORRECOVERY=ANTLR3_FALSE;
            	        }
            	        else 
            	        {
            	            CONSTRUCTEX();
            	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
            	            EXCEPTION->expectingSet = &FOLLOW_set_in_term0389;
            	            RECOVERFROMMISMATCHEDSET(&FOLLOW_set_in_term0389);    goto ruleterm0Ex;
            	        }

            	        FOLLOWPUSH(FOLLOW_term1_in_term0408);
            	        rhs=term1(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleterm0Ex;
            	        }

            	        {

            	                        switch (op->getType(op))
            	                        {
            	                        case BOOL_AND:
            	                            result = (result != 0 && rhs != 0) ? 1 : 0;
            	                            break;
            	                        case BOOL_OR:
            	                            result = (result != 0 || rhs != 0) ? 1 : 0;
            	                            break;
            	                        case BIT_AND:
            	                            result &= rhs;
            	                            break;
            	                        case BIT_OR:
            	                            result |= rhs;
            	                            break;
            	                        }
            	                    
            	        }

            	    }
            	    break;

            	default:
            	    goto loop2;	/* break out of the loop */
            	    break;
                }
            }
            loop2: ; /* Jump out to here if this rule does not match */


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleterm0Ex; /* Prevent compiler warnings */
    ruleterm0Ex: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return result;
}
/* $ANTLR end term0 */

/** 
 * $ANTLR start term1
 * NMakeExpression.g3pl:108:1: term1 returns [int result] : lhs= term2 (op= ( EQUAL | NOT_EQUAL | LESS_THAN | GREATER_THAN | EQUAL_OR_LESS_THAN | EQUAL_OR_GREATER_THAN ) rhs= term2 )* ;
 */
static int
term1(pNMakeExpressionParser ctx)
{   
    int result = 0;

    pANTLR3_COMMON_TOKEN    op;
    int lhs;
    #undef	RETURN_TYPE_lhs
    #define	RETURN_TYPE_lhs int

    int rhs;
    #undef	RETURN_TYPE_rhs
    #define	RETURN_TYPE_rhs int

    /* Initialize rule variables
     */


    op       = NULL;
    lhs = 0;
    rhs = 0;

    {
        // NMakeExpression.g3pl:108:28: (lhs= term2 (op= ( EQUAL | NOT_EQUAL | LESS_THAN | GREATER_THAN | EQUAL_OR_LESS_THAN | EQUAL_OR_GREATER_THAN ) rhs= term2 )* )
        // NMakeExpression.g3pl:109:5: lhs= term2 (op= ( EQUAL | NOT_EQUAL | LESS_THAN | GREATER_THAN | EQUAL_OR_LESS_THAN | EQUAL_OR_GREATER_THAN ) rhs= term2 )*
        {
            FOLLOWPUSH(FOLLOW_term2_in_term1446);
            lhs=term2(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleterm1Ex;
            }

            {

                            result = lhs;
                        
            }

            // NMakeExpression.g3pl:113:5: (op= ( EQUAL | NOT_EQUAL | LESS_THAN | GREATER_THAN | EQUAL_OR_LESS_THAN | EQUAL_OR_GREATER_THAN ) rhs= term2 )*

            for (;;)
            {
                int alt3=2;
                {
                   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                    */
                    int LA3_0 = LA(1);
                    if ( (((LA3_0 >= EQUAL) && (LA3_0 <= EQUAL_OR_GREATER_THAN))) ) 
                    {
                        alt3=1;
                    }

                }
                switch (alt3) 
                {
            	case 1:
            	    // NMakeExpression.g3pl:113:7: op= ( EQUAL | NOT_EQUAL | LESS_THAN | GREATER_THAN | EQUAL_OR_LESS_THAN | EQUAL_OR_GREATER_THAN ) rhs= term2
            	    {
            	        op=(pANTLR3_COMMON_TOKEN)LT(1);
            	        if ( ((LA(1) >= EQUAL) && (LA(1) <= EQUAL_OR_GREATER_THAN)) )
            	        {
            	            CONSUME();
            	            PERRORRECOVERY=ANTLR3_FALSE;
            	        }
            	        else 
            	        {
            	            CONSTRUCTEX();
            	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
            	            EXCEPTION->expectingSet = &FOLLOW_set_in_term1466;
            	            RECOVERFROMMISMATCHEDSET(&FOLLOW_set_in_term1466);    goto ruleterm1Ex;
            	        }

            	        FOLLOWPUSH(FOLLOW_term2_in_term1492);
            	        rhs=term2(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleterm1Ex;
            	        }

            	        {

            	                        switch (op->getType(op))
            	                        {
            	                        case EQUAL:
            	                            result = (result == rhs);
            	                            break;
            	                        case NOT_EQUAL:
            	                            result = (result != rhs);
            	                            break;
            	                        case LESS_THAN:
            	                            result = (result < rhs);
            	                            break;
            	                        case GREATER_THAN:
            	                            result = (result > rhs);
            	                            break;
            	                        case EQUAL_OR_LESS_THAN:
            	                            result = (result <= rhs);
            	                            break;
            	                        case EQUAL_OR_GREATER_THAN:
            	                            result = (result >= rhs);
            	                            break;
            	                        }
            	                    
            	        }

            	    }
            	    break;

            	default:
            	    goto loop3;	/* break out of the loop */
            	    break;
                }
            }
            loop3: ; /* Jump out to here if this rule does not match */


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleterm1Ex; /* Prevent compiler warnings */
    ruleterm1Ex: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return result;
}
/* $ANTLR end term1 */

/** 
 * $ANTLR start term2
 * NMakeExpression.g3pl:140:1: term2 returns [int result] : lhs= term3 (op= ( SHIFT_LEFT | SHIFT_RIGHT ) rhs= term3 )* ;
 */
static int
term2(pNMakeExpressionParser ctx)
{   
    int result = 0;

    pANTLR3_COMMON_TOKEN    op;
    int lhs;
    #undef	RETURN_TYPE_lhs
    #define	RETURN_TYPE_lhs int

    int rhs;
    #undef	RETURN_TYPE_rhs
    #define	RETURN_TYPE_rhs int

    /* Initialize rule variables
     */


    op       = NULL;
    lhs = 0;
    rhs = 0;

    {
        // NMakeExpression.g3pl:140:28: (lhs= term3 (op= ( SHIFT_LEFT | SHIFT_RIGHT ) rhs= term3 )* )
        // NMakeExpression.g3pl:141:5: lhs= term3 (op= ( SHIFT_LEFT | SHIFT_RIGHT ) rhs= term3 )*
        {
            FOLLOWPUSH(FOLLOW_term3_in_term2532);
            lhs=term3(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleterm2Ex;
            }

            {

                            result = lhs;
                        
            }

            // NMakeExpression.g3pl:145:5: (op= ( SHIFT_LEFT | SHIFT_RIGHT ) rhs= term3 )*

            for (;;)
            {
                int alt4=2;
                {
                   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                    */
                    int LA4_0 = LA(1);
                    if ( (((LA4_0 >= SHIFT_LEFT) && (LA4_0 <= SHIFT_RIGHT))) ) 
                    {
                        alt4=1;
                    }

                }
                switch (alt4) 
                {
            	case 1:
            	    // NMakeExpression.g3pl:145:7: op= ( SHIFT_LEFT | SHIFT_RIGHT ) rhs= term3
            	    {
            	        op=(pANTLR3_COMMON_TOKEN)LT(1);
            	        if ( ((LA(1) >= SHIFT_LEFT) && (LA(1) <= SHIFT_RIGHT)) )
            	        {
            	            CONSUME();
            	            PERRORRECOVERY=ANTLR3_FALSE;
            	        }
            	        else 
            	        {
            	            CONSTRUCTEX();
            	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
            	            EXCEPTION->expectingSet = &FOLLOW_set_in_term2552;
            	            RECOVERFROMMISMATCHEDSET(&FOLLOW_set_in_term2552);    goto ruleterm2Ex;
            	        }

            	        FOLLOWPUSH(FOLLOW_term3_in_term2562);
            	        rhs=term3(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleterm2Ex;
            	        }

            	        {

            	                        switch (op->getType(op))
            	                        {
            	                        case SHIFT_LEFT:
            	                            result = (result << rhs);
            	                            break;
            	                        case SHIFT_RIGHT:
            	                            result = (result >> rhs);
            	                            break;
            	                        }
            	                    
            	        }

            	    }
            	    break;

            	default:
            	    goto loop4;	/* break out of the loop */
            	    break;
                }
            }
            loop4: ; /* Jump out to here if this rule does not match */


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleterm2Ex; /* Prevent compiler warnings */
    ruleterm2Ex: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return result;
}
/* $ANTLR end term2 */

/** 
 * $ANTLR start term3
 * NMakeExpression.g3pl:160:1: term3 returns [int result] : lhs= term4 (op= ( PLUS | MINUS ) rhs= term4 )* ;
 */
static int
term3(pNMakeExpressionParser ctx)
{   
    int result = 0;

    pANTLR3_COMMON_TOKEN    op;
    int lhs;
    #undef	RETURN_TYPE_lhs
    #define	RETURN_TYPE_lhs int

    int rhs;
    #undef	RETURN_TYPE_rhs
    #define	RETURN_TYPE_rhs int

    /* Initialize rule variables
     */


    op       = NULL;
    lhs = 0;
    rhs = 0;

    {
        // NMakeExpression.g3pl:160:27: (lhs= term4 (op= ( PLUS | MINUS ) rhs= term4 )* )
        // NMakeExpression.g3pl:161:5: lhs= term4 (op= ( PLUS | MINUS ) rhs= term4 )*
        {
            FOLLOWPUSH(FOLLOW_term4_in_term3601);
            lhs=term4(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleterm3Ex;
            }

            {

                            result = lhs;
                        
            }

            // NMakeExpression.g3pl:165:5: (op= ( PLUS | MINUS ) rhs= term4 )*

            for (;;)
            {
                int alt5=2;
                {
                   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                    */
                    int LA5_0 = LA(1);
                    if ( (((LA5_0 >= PLUS) && (LA5_0 <= MINUS))) ) 
                    {
                        alt5=1;
                    }

                }
                switch (alt5) 
                {
            	case 1:
            	    // NMakeExpression.g3pl:165:7: op= ( PLUS | MINUS ) rhs= term4
            	    {
            	        op=(pANTLR3_COMMON_TOKEN)LT(1);
            	        if ( ((LA(1) >= PLUS) && (LA(1) <= MINUS)) )
            	        {
            	            CONSUME();
            	            PERRORRECOVERY=ANTLR3_FALSE;
            	        }
            	        else 
            	        {
            	            CONSTRUCTEX();
            	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
            	            EXCEPTION->expectingSet = &FOLLOW_set_in_term3621;
            	            RECOVERFROMMISMATCHEDSET(&FOLLOW_set_in_term3621);    goto ruleterm3Ex;
            	        }

            	        FOLLOWPUSH(FOLLOW_term4_in_term3631);
            	        rhs=term4(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleterm3Ex;
            	        }

            	        {

            	                        switch (op->getType(op))
            	                        {
            	                        case PLUS:
            	                            result += rhs;
            	                            break;
            	                        case MINUS:
            	                            result -= rhs;
            	                            break;
            	                        }
            	                    
            	        }

            	    }
            	    break;

            	default:
            	    goto loop5;	/* break out of the loop */
            	    break;
                }
            }
            loop5: ; /* Jump out to here if this rule does not match */


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleterm3Ex; /* Prevent compiler warnings */
    ruleterm3Ex: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return result;
}
/* $ANTLR end term3 */

/** 
 * $ANTLR start term4
 * NMakeExpression.g3pl:180:1: term4 returns [int result] : lhs= term5 (op= ( MULT | DIV | MOD ) rhs= term5 )* ;
 */
static int
term4(pNMakeExpressionParser ctx)
{   
    int result = 0;

    pANTLR3_COMMON_TOKEN    op;
    int lhs;
    #undef	RETURN_TYPE_lhs
    #define	RETURN_TYPE_lhs int

    int rhs;
    #undef	RETURN_TYPE_rhs
    #define	RETURN_TYPE_rhs int

    /* Initialize rule variables
     */


    op       = NULL;
    lhs = 0;
    rhs = 0;

    {
        // NMakeExpression.g3pl:180:27: (lhs= term5 (op= ( MULT | DIV | MOD ) rhs= term5 )* )
        // NMakeExpression.g3pl:181:5: lhs= term5 (op= ( MULT | DIV | MOD ) rhs= term5 )*
        {
            FOLLOWPUSH(FOLLOW_term5_in_term4670);
            lhs=term5(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleterm4Ex;
            }

            {

                            result = lhs;
                        
            }

            // NMakeExpression.g3pl:185:5: (op= ( MULT | DIV | MOD ) rhs= term5 )*

            for (;;)
            {
                int alt6=2;
                {
                   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                    */
                    int LA6_0 = LA(1);
                    if ( (((LA6_0 >= MULT) && (LA6_0 <= MOD))) ) 
                    {
                        alt6=1;
                    }

                }
                switch (alt6) 
                {
            	case 1:
            	    // NMakeExpression.g3pl:185:7: op= ( MULT | DIV | MOD ) rhs= term5
            	    {
            	        op=(pANTLR3_COMMON_TOKEN)LT(1);
            	        if ( ((LA(1) >= MULT) && (LA(1) <= MOD)) )
            	        {
            	            CONSUME();
            	            PERRORRECOVERY=ANTLR3_FALSE;
            	        }
            	        else 
            	        {
            	            CONSTRUCTEX();
            	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
            	            EXCEPTION->expectingSet = &FOLLOW_set_in_term4690;
            	            RECOVERFROMMISMATCHEDSET(&FOLLOW_set_in_term4690);    goto ruleterm4Ex;
            	        }

            	        FOLLOWPUSH(FOLLOW_term5_in_term4704);
            	        rhs=term5(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleterm4Ex;
            	        }

            	        {

            	                        switch (op->getType(op))
            	                        {
            	                        case MULT:
            	                            result *= rhs;
            	                            break;
            	                        case DIV:
            	                            result /= rhs;
            	                            break;
            	                        case MOD:
            	                            result = result % rhs;
            	                            break;
            	                        }
            	                    
            	        }

            	    }
            	    break;

            	default:
            	    goto loop6;	/* break out of the loop */
            	    break;
                }
            }
            loop6: ; /* Jump out to here if this rule does not match */


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleterm4Ex; /* Prevent compiler warnings */
    ruleterm4Ex: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return result;
}
/* $ANTLR end term4 */

/** 
 * $ANTLR start term5
 * NMakeExpression.g3pl:203:1: term5 returns [int result] : (op= ( MINUS | BIT_NOT | BOOL_NOT ) )? v= primary ;
 */
static int
term5(pNMakeExpressionParser ctx)
{   
    int result = 0;

    pANTLR3_COMMON_TOKEN    op;
    int v;
    #undef	RETURN_TYPE_v
    #define	RETURN_TYPE_v int

    /* Initialize rule variables
     */


    op       = NULL;
    v = 0;

    {
        // NMakeExpression.g3pl:203:27: ( (op= ( MINUS | BIT_NOT | BOOL_NOT ) )? v= primary )
        // NMakeExpression.g3pl:204:5: (op= ( MINUS | BIT_NOT | BOOL_NOT ) )? v= primary
        {

            // NMakeExpression.g3pl:204:7: (op= ( MINUS | BIT_NOT | BOOL_NOT ) )?
            {
                int alt7=2;
                {
                    int LA7_0 = LA(1);
                    if ( (LA7_0 == MINUS || ((LA7_0 >= BIT_NOT) && (LA7_0 <= BOOL_NOT))) ) 
                    {
                        alt7=1;
                    }
                }
                switch (alt7) 
                {
            	case 1:
            	    // NMakeExpression.g3pl:204:7: op= ( MINUS | BIT_NOT | BOOL_NOT )
            	    {
            	        op=(pANTLR3_COMMON_TOKEN)LT(1);
            	        if ( LA(1) == MINUS || ((LA(1) >= BIT_NOT) && (LA(1) <= BOOL_NOT)) )
            	        {
            	            CONSUME();
            	            PERRORRECOVERY=ANTLR3_FALSE;
            	        }
            	        else 
            	        {
            	            CONSTRUCTEX();
            	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
            	            EXCEPTION->expectingSet = &FOLLOW_set_in_term5743;
            	            RECOVERFROMMISMATCHEDSET(&FOLLOW_set_in_term5743);    goto ruleterm5Ex;
            	        }


            	    }
            	    break;

                }
            }
            FOLLOWPUSH(FOLLOW_primary_in_term5758);
            v=primary(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleterm5Ex;
            }

            {

                            if (!op)
                                result = v;
                            else
                                switch (op->getType(op))
                                {
                                case MINUS:
                                    result = -v;
                                    break;
                                case BIT_NOT:
                                    result = ~v;
                                    break;
                                case BOOL_NOT:
                                    result = (v != 0) ? 0 : 1;
                                    break;
                                }
                        
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleterm5Ex; /* Prevent compiler warnings */
    ruleterm5Ex: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return result;
}
/* $ANTLR end term5 */

/** 
 * $ANTLR start primary
 * NMakeExpression.g3pl:224:1: primary returns [int result] : (n= NUMBER | DEFINED '(' t= ( STRING | IDENTIFIER ) ')' | t= EXIST | '(' n2= term0 ')' );
 */
static int
primary(pNMakeExpressionParser ctx)
{   
    int result = 0;

    pANTLR3_COMMON_TOKEN    n;
    pANTLR3_COMMON_TOKEN    t;
    int n2;
    #undef	RETURN_TYPE_n2
    #define	RETURN_TYPE_n2 int

    /* Initialize rule variables
     */


    n       = NULL;
    t       = NULL;
    n2 = 0;

    {
        {
            //  NMakeExpression.g3pl:224:29: (n= NUMBER | DEFINED '(' t= ( STRING | IDENTIFIER ) ')' | t= EXIST | '(' n2= term0 ')' )
            
            ANTLR3_UINT32 alt8;

            alt8=4;

            switch ( LA(1) ) 
            {
            case NUMBER:
            	{
            		alt8=1;
            	}
                break;
            case DEFINED:
            	{
            		alt8=2;
            	}
                break;
            case EXIST:
            	{
            		alt8=3;
            	}
                break;
            case 32:
            	{
            		alt8=4;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 8;
                EXCEPTION->state        = 0;


                goto ruleprimaryEx;
            }

            switch (alt8) 
            {
        	case 1:
        	    // NMakeExpression.g3pl:225:5: n= NUMBER
        	    {
        	        n = (pANTLR3_COMMON_TOKEN) MATCHT(NUMBER, &FOLLOW_NUMBER_in_primary790); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleprimaryEx;
        	        }

        	        {

        	                        pANTLR3_STRING text = n->getText(n);
        	                        result = text->toInt32(text);
        	                    
        	        }

        	    }
        	    break;
        	case 2:
        	    // NMakeExpression.g3pl:230:5: DEFINED '(' t= ( STRING | IDENTIFIER ) ')'
        	    {
        	         MATCHT(DEFINED, &FOLLOW_DEFINED_in_primary806); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleprimaryEx;
        	        }

        	         MATCHT(32, &FOLLOW_32_in_primary808); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleprimaryEx;
        	        }

        	        t=(pANTLR3_COMMON_TOKEN)LT(1);
        	        if ( LA(1) == STRING || LA(1) == IDENTIFIER )
        	        {
        	            CONSUME();
        	            PERRORRECOVERY=ANTLR3_FALSE;
        	        }
        	        else 
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
        	            EXCEPTION->expectingSet = &FOLLOW_set_in_primary812;
        	            RECOVERFROMMISMATCHEDSET(&FOLLOW_set_in_primary812);    goto ruleprimaryEx;
        	        }

        	         MATCHT(33, &FOLLOW_33_in_primary820); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleprimaryEx;
        	        }

        	        {

        	                        result = isMacroDefined(t->getText(t));
        	                    
        	        }

        	    }
        	    break;
        	case 3:
        	    // NMakeExpression.g3pl:234:5: t= EXIST
        	    {
        	        t = (pANTLR3_COMMON_TOKEN) MATCHT(EXIST, &FOLLOW_EXIST_in_primary838); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleprimaryEx;
        	        }

        	        {

        	                        result = isFileExisting(t->getText(t));
        	                    
        	        }

        	    }
        	    break;
        	case 4:
        	    // NMakeExpression.g3pl:238:5: '(' n2= term0 ')'
        	    {
        	         MATCHT(32, &FOLLOW_32_in_primary854); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleprimaryEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_term0_in_primary858);
        	        n2=term0(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleprimaryEx;
        	        }

        	         MATCHT(33, &FOLLOW_33_in_primary860); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleprimaryEx;
        	        }

        	        {

        	                        result = n2;
        	                    
        	        }

        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto ruleprimaryEx; /* Prevent compiler warnings */
    ruleprimaryEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return result;
}
/* $ANTLR end primary */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */

 
 



/* End of code
 * =============================================================================
 */
